//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial  class oa_student_course
{
    public  virtual int Id { get; set; }
    public  virtual string Name { get; set; }
    public  virtual decimal Price { get; set; }
}
