//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHibernate.CMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial  class sys_token
    {
        public  virtual int id { get; set; }
        public  virtual string DevId { get; set; }
        public  virtual string AppId { get; set; }
        public  virtual string CertId { get; set; }
        public  virtual string ApiToken { get; set; }
        public  virtual string ebay_account { get; set; }
        public  virtual string name_cn { get; set; }
        public  virtual string name_en { get; set; }
    }
}
