//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHibernate.CMS.Libs
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class itCMSAccountEntities : DbContext
    {
        public itCMSAccountEntities()
            : base("name=itCMSAccountEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sys_user> sys_user { get; set; }
        public DbSet<sys_module> sys_module { get; set; }
        public DbSet<sys_group> sys_group { get; set; }
        public DbSet<sys_action> sys_action { get; set; }
        public DbSet<sys_group_user> sys_group_user { get; set; }
        public DbSet<sys_acl_user> sys_acl_user { get; set; }
        public DbSet<sys_acl_group> sys_acl_group { get; set; }
        public DbSet<sys_Department> sys_Department { get; set; }
        public DbSet<sys_config> sys_config { get; set; }
        public DbSet<sys_token> sys_token { get; set; }
    }
}
