//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHibernate.CMS.Libs
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_token
    {
        public int id { get; set; }
        public string DevId { get; set; }
        public string AppId { get; set; }
        public string CertId { get; set; }
        public string ApiToken { get; set; }
        public string ebay_account { get; set; }
        public string name_cn { get; set; }
        public string name_en { get; set; }
    }
}
