//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHibernate.CMS.Libs
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_user
    {
        public int userID { get; set; }
        public string userAccount { get; set; }
        public string userPasswd { get; set; }
        public string telephone { get; set; }
        public string email { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> departID { get; set; }
        public string acctounName { get; set; }
    }
}
