//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHibernate.CMS.Libs
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_module
    {
        public int moduleID { get; set; }
        public string moduleKey { get; set; }
        public string moduleName { get; set; }
        public int parentID { get; set; }
        public string urls { get; set; }
        public bool isMenu { get; set; }
        public bool isDisplay { get; set; }
        public Nullable<int> sort { get; set; }
        public string icon { get; set; }
        public Nullable<int> class_layer { get; set; }
    }
}
